### PR TITLE
Extension: duplicate columns handler

### PR DESCRIPTION
**Pull request by TSMMark**
Revisiting Plugin: WarningSelect #1 as a dataset extension.

### CODE REVIEW

**Comment by TSMMark** [comment]
@JeremyEvans you were right this is much better (:

Let me know if it needs anything else other than docs.

**Comment by jeremyevans** [comment]
Thanks, this version looks mostly ready, I'd just recommend a few changes:

Store :on_duplicate_columns in the dataset's options hash instead of an instance variable.

Use consistent format for exception raising: `raise Error, msg`, not `raise Error.new(msg)`.

In `columns=`, instead of assigning to `@columns` first, pass cols to handle_duplicate_columns, and assign at the end.

Use `opts.fetch(:on_duplicate_columns){db.opts.fetch(:on_duplicate_columns, :warn)}` to get the handler

Make Sequel::DuplicateColumnHandler the main module (remove the DatasetMethods part), and rename the error class to Sequel::DuplicateColumnError

In the tests, override the warn method in the dataset instead of using capture_io, and just inline the code instead of adding your own must_\* methods. Also, check that the on_duplicate_columns proc yields the columns.

**Comment by TSMMark** [comment]
@jeremyevans All set. Let me know if it's ready and I'll start adding docs.

**Comment by jeremyevans** [comment]
This looks good.  I may make a minor tweak here or there, but it's ready for docs, then please submit a pull request.  Thanks for all of your hard work on this.

**Comment by TSMMark** [comment]
Closing this PR and submitting one. https://github.com/jeremyevans/sequel/pull/1175

**Pull request closed without merging**
